# VoIP Dialer Konfiguration
# Pfad: /etc/voip-dialer/config.yml oder ./config.yml

# SIP/VoIP Server Konfiguration
sip:
  server: "192.168.1.100"          # IP-Adresse Ihres FreePBX Servers
  username: "1001"                 # SIP-Benutzername 
  password: "geheim123"            # SIP-Passwort
  local_port: 5060                 # Lokaler SIP-Port (Standard: 5060)

# GPIO Button Konfiguration
gpio:
  buttons:
    - pin: 17                      # GPIO Pin 17
      name: "Notruf Polizei"       # Beschreibung
      number: "110"                # Zu wählende Nummer
    
    - pin: 27                      # GPIO Pin 27  
      name: "Notruf Feuerwehr"     # Beschreibung
      number: "112"                # Zu wählende Nummer

# Anruf-Einstellungen
call:
  duration_seconds: 30             # Automatisches Auflegen nach X Sekunden
  auto_answer: false               # Automatisches Annehmen eingehender Anrufe

# Audio-Konfiguration (RaspAudio Mic Ultra+)
audio:
  input_device: "default"          # Audio-Eingabegerät
  output_device: "default"         # Audio-Ausgabegerät
  sample_rate: 8000               # Samplerate für VoIP (8kHz Standard)
  echo_cancellation: true          # Echo-Unterdrückung aktivieren (wichtig!)
  echo_tail_length: 200           # Echo-Tail in ms (100-800, Standard: 200)
  aec_level: 4                     # AEC-Level (0-4, höher = aggressiver)

# Logging-Konfiguration
logging:
  level: "INFO"                    # DEBUG, INFO, WARNING, ERROR
  file: "/var/log/voip-dialer.log" # Log-Datei Pfad
  max_size_mb: 10                  # Maximale Log-Dateigröße
  backup_count: 5                  # Anzahl Backup-Log-Dateien

# System-Einstellungen
system:
  daemon: true                     # Als Service/Daemon laufen
  pid_file: "/var/run/voip-dialer.pid"  # PID-Datei für Service
  user: "voip"                     # Benutzer unter dem der Service läuft